/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListYourVanRouteImport } from './routes/list-your-van'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as VanSlugIdxRouteImport } from './routes/van.$slug.$idx'

const ListYourVanRoute = ListYourVanRouteImport.update({
  id: '/list-your-van',
  path: '/list-your-van',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VanSlugIdxRoute = VanSlugIdxRouteImport.update({
  id: '/van/$slug/$idx',
  path: '/van/$slug/$idx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/cart': typeof CartRoute
  '/destinations': typeof DestinationsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-your-van': typeof ListYourVanRoute
  '/category/$slug': typeof CategorySlugRoute
  '/van/$slug/$idx': typeof VanSlugIdxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/cart': typeof CartRoute
  '/destinations': typeof DestinationsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-your-van': typeof ListYourVanRoute
  '/category/$slug': typeof CategorySlugRoute
  '/van/$slug/$idx': typeof VanSlugIdxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy': typeof BuyRoute
  '/cart': typeof CartRoute
  '/destinations': typeof DestinationsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-your-van': typeof ListYourVanRoute
  '/category/$slug': typeof CategorySlugRoute
  '/van/$slug/$idx': typeof VanSlugIdxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy'
    | '/cart'
    | '/destinations'
    | '/how-it-works'
    | '/list-your-van'
    | '/category/$slug'
    | '/van/$slug/$idx'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy'
    | '/cart'
    | '/destinations'
    | '/how-it-works'
    | '/list-your-van'
    | '/category/$slug'
    | '/van/$slug/$idx'
  id:
    | '__root__'
    | '/'
    | '/buy'
    | '/cart'
    | '/destinations'
    | '/how-it-works'
    | '/list-your-van'
    | '/category/$slug'
    | '/van/$slug/$idx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyRoute: typeof BuyRoute
  CartRoute: typeof CartRoute
  DestinationsRoute: typeof DestinationsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListYourVanRoute: typeof ListYourVanRoute
  CategorySlugRoute: typeof CategorySlugRoute
  VanSlugIdxRoute: typeof VanSlugIdxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/list-your-van': {
      id: '/list-your-van'
      path: '/list-your-van'
      fullPath: '/list-your-van'
      preLoaderRoute: typeof ListYourVanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/van/$slug/$idx': {
      id: '/van/$slug/$idx'
      path: '/van/$slug/$idx'
      fullPath: '/van/$slug/$idx'
      preLoaderRoute: typeof VanSlugIdxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyRoute: BuyRoute,
  CartRoute: CartRoute,
  DestinationsRoute: DestinationsRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListYourVanRoute: ListYourVanRoute,
  CategorySlugRoute: CategorySlugRoute,
  VanSlugIdxRoute: VanSlugIdxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
